version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/django-backend:latest
    container_name: backend
    restart: always
    expose:
      - "8000"
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
    networks:
      - app-network

  frontend:
    image: ${DOCKER_USERNAME}/react-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
