version: '3.8'

services:
  backend:
    image: ${DOCKER_USERNAME}/django-backend:latest
    container_name: django_backend_prod
    restart: always
    ports:
      - "8000:8000"
    environment:
      - DEBUG=False
      - DJANGO_ALLOWED_HOSTS=*
      - CORS_ALLOW_ALL_ORIGINS=True

  frontend:
    image: ${DOCKER_USERNAME}/react-frontend:latest
    container_name: react_frontend_prod
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge