name: CI Pipeline

on:
  push:
    branches:
      - main
      - master

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build images
        run: |
          docker build -t backend:test ./backend
          docker build -t frontend:test ./frontend

      - name: Run containers
        run: |
          docker compose up -d
          sleep 20
          docker compose ps

      - name: Test backend
        run: |
          curl -f http://localhost:8000/api/hello/

      - name: Test frontend
        run: |
          curl -f http://localhost:80/

      - name: Cleanup
        if: always()
        run: |
          docker compose down
